### PR TITLE
v1.0.0 Release

### PR DESCRIPTION
**Pull request by igorescobar**
This PR introduces the `v1.0.0` of the Elixir SDK.
Website Docs: https://github.com/configcat/docs/pull/21

# Special Thanks
## [Drover](https://joindrover.com/) 🚗 
For allowing me to work on this project and contribute directly to the community/Elixir's ecosystem.

## Randy Coulman 🎖️ 
@randycoulman thanks a lot for joining me on this initiative. I've added you separately here because I know you've worked completely outside of your working hours on this project with me and making a fully-fledged Elixir SDK came 100% from your personal efforts.

## [InfluxData](https://www.influxdata.com/)
Thanks again to @randycoulman and his team at [InfluxData](https://www.influxdata.com/) which gave us an initial version of this SDK so we didn't need to start entirely from scratch. Friends from InfluxData ❤️ :
- [Iris Scholten](https://github.com/ischolten)
- [Delmer Reed](https://github.com/OfTheDelmer)
- [Marc Delagrammatikas](https://github.com/marcdel)
- [Mansi Gandhi](https://github.com/mansimg)
- [Kristin Albright](https://github.com/KristinA64)
- [Nick Stalter](https://github.com/distortia)

# ConfigCat Team
@laliconfigcat and his team for embracing the challenge with us, providing all the technical guidance required to make it happen.

### CODE REVIEW

**Comment by z4kn4fein** [comment]
😄

Just kidding ofc, it's just my first encounter with Elixir. 😃  
I'm really impressed with the work and effort you put in this contribution guys, amazing job! We really appreciate this!

**Comment by randycoulman** [comment]
We'll want to update this with the final merged PRs to v1.0.0 before merging, but I'm so glad we're at this milestone!

**Comment by igorescobar** [comment]
> We'll want to update this with the final merged PRs to v1.0.0 before merging, but I'm so glad we're at this milestone!

It happens automatically 👍

**Comment by randycoulman** [comment]
Oh, yeah, of course 🤦 .  I'll be fully awake soon, I promise!

**Review by z4kn4fein — APPROVED** [review]
❤️

**Review by laliconfigcat — APPROVED** [review]

**Pull request merged**
